# Generated by Django 2.2.3 on 2019-07-15 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombres del Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('telefono1', models.CharField(max_length=20, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(max_length=20, verbose_name='Telefono 2')),
                ('oferta', ckeditor.fields.RichTextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo/ Autor Desactivado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombres del Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('telefono1', models.CharField(max_length=20, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(max_length=20, verbose_name='Telefono 2')),
                ('experiencia', ckeditor.fields.RichTextField()),
                ('ofertas', ckeditor.fields.RichTextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo/ Autor Desactivado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255, verbose_name='Nombres del Autor')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombres del Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('telefono1', models.CharField(max_length=20, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(max_length=20, verbose_name='Telefono 2')),
                ('oferta', ckeditor.fields.RichTextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo/ Autor Desactivado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
